# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql


  username: may
  password: '123'
  host: localhost
  port: 5432
  pool: 5


development:
  <<: *default
  database: imaginedb


test:
  <<: *default
  database: imaginedb
  pool: 5
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
  database: imaginedb
  pool: 5
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
