# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  
  pool: 5
  username: may
  password: '123'
  host: localhost
  port: 5432

development:
  <<: *default
  database: imaginedb


test:
  <<: *default
  database: imaginedb

production:
  <<: *default
  database: imaginedb
